# Generated by Django 4.1.1 on 2022-10-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('countries', '0001_initial'), ('countries', '0002_alter_countryeconomicfreedomindex_country_iso_code_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryEconomicFreedomIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('score', models.FloatField()),
                ('country_iso_code', models.CharField(max_length=4)),
                ('year', models.IntegerField()),
            ],
            options={
                'unique_together': {('country_iso_code', 'year')},
            },
        ),
    ]
