# Generated by Django 4.1.1 on 2022-12-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPayingTaxesIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('year', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='countries.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CountryEconomicFreedomIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('year', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to='countries.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='countrypayingtaxesindex',
            constraint=models.UniqueConstraint(fields=('country', 'year'), name='countries_countrypayingtaxesindex_unique_country_year'),
        ),
        migrations.AddConstraint(
            model_name='countryeconomicfreedomindex',
            constraint=models.UniqueConstraint(fields=('country', 'year'), name='countries_countryeconomicfreedomindex_unique_country_year'),
        ),
    ]
