# Generated by Django 4.1.1 on 2022-12-30 06:36
import pycountry
from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def populate_countries(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Country = apps.get_model('countries', 'Country')
    with open("countries/migrations/countries.list", "r") as file:
        for line in file.readlines():
            country_name = line.strip()
            search_result = pycountry.countries.search_fuzzy(country_name)[0]
            Country.objects.create(name=search_result.name, iso_code=search_result.alpha_3)


class Migration(migrations.Migration):
    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_countries, reverse_code=migrations.RunPython.noop),
    ]
