# Generated by Django 4.1.1 on 2022-09-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryeconomicfreedomindex',
            name='country_iso_code',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryeconomicfreedomindex',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
