# Generated by Django 4.1.1 on 2022-09-25 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_countryeconomicfreedomindex_country_iso_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='countryeconomicfreedomindex',
            unique_together={('country_iso_code', 'year')},
        ),
    ]
