# Generated by Django 4.1.1 on 2022-12-31 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_countrytotaltradevalue_delete_countryimportsvalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryMilitaryStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('year', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='countries.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='countrymilitarystrength',
            constraint=models.UniqueConstraint(fields=('country', 'year'), name='countries_countrymilitarystrength_unique_country_year'),
        ),
    ]
