# Generated by Django 4.1.1 on 2022-12-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_countryreservecurrency'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryGDP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('year', models.IntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='countries.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='countrygdp',
            constraint=models.UniqueConstraint(fields=('country', 'year'), name='countries_countrygdp_unique_country_year'),
        ),
    ]
