# Generated by Django 4.1.1 on 2022-12-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_countrygdp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryeconomicfreedomindex',
            old_name='score',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='countrygdp',
            old_name='score',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='countrypayingtaxesindex',
            old_name='score',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='countrysuiciderate',
            old_name='score',
            new_name='value',
        ),
    ]
