# Generated by Django 4.1.1 on 2022-10-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LazyPortfolioTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.lazyportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_ratio', models.FloatField()),
                ('inception_date', models.DateField()),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Bonds', 'Bonds'), ('Comm', 'Commodities'), ('Stocks', 'Stocks')], default='Stocks', max_length=10)),
                ('equivalents', models.ManyToManyField(blank=True, to='portfolios.ticker')),
                ('portfolio', models.ManyToManyField(through='portfolios.LazyPortfolioTicker', to='portfolios.lazyportfolio')),
            ],
        ),
        migrations.AddField(
            model_name='lazyportfolioticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.ticker'),
        ),
    ]
