# Generated by Django 4.1.1 on 2022-10-08 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('portfolios', '0001_initial'), ('portfolios', '0002_remove_ticker_type_ticker_asset_type_ticker_name_and_more'), ('portfolios', '0003_alter_ticker_expense_ratio'), ('portfolios', '0004_alter_ticker_inception_date')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LazyPortfolioTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.lazyportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_ratio', models.FloatField(null=True)),
                ('inception_date', models.DateField(null=True)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('equivalents', models.ManyToManyField(blank=True, to='portfolios.ticker')),
                ('portfolio', models.ManyToManyField(through='portfolios.LazyPortfolioTicker', to='portfolios.lazyportfolio')),
                ('asset_type', models.CharField(choices=[('Bonds', 'Bonds'), ('Commodities', 'Commodities'), ('Real Estate', 'Real Estate'), ('Stocks', 'Stocks')], default='Stocks', max_length=15)),
                ('name', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='lazyportfolioticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.ticker'),
        ),
    ]
