# Generated by Django 4.1.1 on 2022-11-27 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cagr', models.FloatField(blank=True, help_text='Compound annual growth rate', null=True)),
                ('market_correlation', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sharpe', models.FloatField(blank=True, null=True)),
                ('sortino', models.FloatField(blank=True, null=True)),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
            ],
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickers', to='investments.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_ratio', models.FloatField(blank=True, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('Bonds', 'Bonds'), ('Commodities', 'Commodities'), ('Real Estate', 'Real Estate'), ('Stocks', 'Stocks')], default='Stocks', max_length=15)),
                ('equivalents', models.ManyToManyField(blank=True, to='investments.ticker')),
                ('portfolio', models.ManyToManyField(through='investments.PortfolioTicker', to='investments.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolioticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.ticker'),
        ),
    ]
