# Generated by Django 4.1.1 on 2022-11-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LazyPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LazyPortfolioTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.lazyportfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_ratio', models.FloatField(blank=True, null=True)),
                ('inception_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('Bonds', 'Bonds'), ('Commodities', 'Commodities'), ('Real Estate', 'Real Estate'), ('Stocks', 'Stocks')], default='Stocks', max_length=15)),
                ('equivalents', models.ManyToManyField(blank=True, to='investments.ticker')),
                ('portfolio', models.ManyToManyField(through='investments.LazyPortfolioTicker', to='investments.lazyportfolio')),
            ],
        ),
        migrations.AddField(
            model_name='lazyportfolioticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.ticker'),
        ),
    ]
