# Generated by Django 4.1.1 on 2022-11-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lazyportfolio',
            name='max_drawdown',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
