# Generated by Django 4.1.1 on 2022-11-27 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolioticker',
            unique_together={('portfolio', 'ticker')},
        ),
    ]
