# Generated by Django 4.1.1 on 2022-12-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_portfolioticker_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='cagr',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='market_correlation',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='max_drawdown',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='sharpe',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='sortino',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='standard_deviation',
        ),
        migrations.CreateModel(
            name='PortfolioBacktestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cagr', models.FloatField(blank=True, help_text='Compound annual growth rate', null=True)),
                ('market_correlation', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('sharpe', models.FloatField(blank=True, null=True)),
                ('sortino', models.FloatField(blank=True, null=True)),
                ('standard_deviation', models.FloatField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('portfolio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backtest_data', to='investments.portfolio')),
            ],
        ),
    ]
