# Generated by Django 4.1.1 on 2022-11-20 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_lazyportfolio_max_drawdown'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LazyPortfolio',
            new_name='Portfolio',
        ),
    ]
