# Generated by Django 4.1.1 on 2022-11-20 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_rename_lazyportfolio_portfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LazyPortfolioTicker',
            new_name='PortfolioTicker',
        ),
    ]
