# Generated by Django 4.1.1 on 2022-11-21 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_portfolioticker_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioticker',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickers', to='investments.portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolioticker',
            name='ticker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='investments.ticker'),
        ),
    ]
